"""create initial tables

Revision ID: 61c2eac9f8c4
Revises: 
Create Date: 2026-07-21 08:20:54.045066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c2eac9f8c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.Enum('GOOGLE_MEET', 'ZOOM', 'MICROSOFT_TEAMS', 'OTHER', name='meetingplatform'), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('fathom_meeting_id', sa.String(length=255), nullable=True),
    sa.Column('recording_url', sa.String(length=1000), nullable=True),
    sa.Column('transcript_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'RECORDING', 'TRANSCRIBED', 'SUMMARIZED', 'PROPOSAL_GENERATED', 'COMPLETED', 'FAILED', name='meetingstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fathom_meeting_id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=True)
    op.create_table('users',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'SALES_AGENT', 'CLIENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('conversations',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('ADMIN', 'CLIENT', name='speakerrole'), nullable=False),
    sa.Column('speaker_label', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_entities', sa.Text(), nullable=True),
    sa.Column('ai_processed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('CAPTURED', 'REVIEWED', 'PROCESSED', name='conversationstatus'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=True)
    op.create_index(op.f('ix_conversations_meeting_id'), 'conversations', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_conversations_sequence_number'), 'conversations', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_conversations_speaker'), 'conversations', ['speaker'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_timestamp'), 'conversations', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_timestamp'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_speaker'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_sequence_number'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_meeting_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
